networks:
  default:
    driver: bridge
    name: ara-demo

include:
  - services/litellm_with_langfuse.yaml
  - services/minio/service.yaml
  - services/qdrant/service.yaml
  - services/postgres/service.yaml