version: '3.8'

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9002:9000"  # S3 API
      - "9003:9001"  # Web Console
    environment:
      MINIO_ROOT_USER: piotrminio
      MINIO_ROOT_PASSWORD: piotrminio
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"